// src/components/vue/NebTable.vue
<template>
<main>
  
    <div class="chart-container">
  <div class="chart-object"  ref="element"/>
</div>

</main>
</template>

<script>
  

export default {
  name: "NebTable",
  props: ["qStruc"],
  async mounted() {
    await this.qStruc.nebbie.render({
      element: this.$refs.element,
      type: "table",
      fields: ["Name", "=sum(Weight)"],
    });
  }
};
</script>


<style scoped>
    .chart-container {
    height: 500px;
  }

  .chart-object {
    position: relative;
    height: 100%;
  }

  
</style>

// src/components/react/NebTable.jsx
import React, { useEffect, useRef } from "react";

const NebBar = ({ qStruc }) => {
  const element = useRef(null);

  useEffect(async () => {
    if (!qStruc) return;
    await qStruc.nebbie.render({
      element: element.current,
      type: "table",
      fields: ["Name", "=sum(Weight)"],
    });
  }, [qStruc]);

  return (
    <div className="chart-container">
      <div className="chart-object" ref={element} />
    </div>
  );
};

export default NebBar;
